services:
  db:
    image: postgres:15
    restart: unless-stopped
    environment:
      - POSTGRES_USER=postgres
      - POSTGRES_PASSWORD=postgres
      - POSTGRES_DB=storyforge
    volumes:
      - pgdata:/var/lib/postgresql/data
      - ./init.sql:/docker-entrypoint-initdb.d/init.sql
    ports:           # Only for local debugging
      - "5432:5432"

  app:
    build: .
    restart: unless-stopped
    environment:
      - DATABASE_URL=postgresql://postgres:postgres@db:5432/storyforge
      - OPENAI_API_KEY=${OPENAI_API_KEY}
    depends_on:
      - db
    ports:
      - "5001:5000"

volumes:
  pgdata:
